export default [
  {
    number: "1",
    name: "अंबुजदल लोचनी",
    search_txt: [
      "ambujadal lochani",
      "ambujdal",
      "adi shakti narayani",
      "ananta sukha daini",
      "sundaragirinandini",
      "aagamya manamohini",
      "aaghad lila adanashini ho",
      "adya kamal lochani",
      "apurva shobhe sihasani ho",
      "komal tanu virajit koti suryahuni zalakit ho",
      "kapol ghavaghavit kumkum kasturi charchit ho",
      "kanchanmani mandit karni kundal shobhat ho",
      "kanchuki vilsit kase pitambar mirvit ho",
    ],
  },
  {
    number: "2",
    name: "जय जय हो जगदंबे । भवानी त्रैलोक्ये लोचनी ।",
    search_txt: [
      "jay jay ho jagadambe",
      "bhavani trailoke lochani",
      "aarati ovalu janani",
      "aarti owalu janani",
      "pavasi tu nirvani",
      "pawasi tu nirawani",
      "jay jay jagadambe",
      "aadi avasan tu maye",
      "bramhadik vanditi pay",
      "krupa karoni janasi",
      "jadmud udarasi",
      "bhakta bhave ho",
      "santasi atmarup desi",
    ],
  },
  {
    number: "3",
    name: "आरती त्रिपुर सुंदरीची",
    search_txt: [
      "aarti tripur sundarichi",
      "amba bai renukechi",
      "ambabai renukechi",
      "mastaki kumkumachi shobha",
      "lalati shobhe mrugnabha",
      "nasiki mouktikachi prabha",
      "nritya karitase pudhe rambha",
      "mele aale yogini che",
      "charan vanditi ambikeche",
      "katyayani yeuni ganpati ki senapati",
      "chakit saraswati vani khuntali ba sheshachi",
      "varta kay manavachi",
      "aaisa jicha gunmahima",
      "nakale kadapi shruti agama",
      "harihar charan vandi bramha",
      "anki baisali parsurama",
      "pahe rahati shushiti",
      "manorath purvi dasache",
    ],
  },
  {
    number: "4",
    name: "लव मज लागला",
    search_txt: [
      "lava maja lagala",
      "bheda bheda kaicha",
      "bedha behd kaicha",
      "aala kantala vishayacha",
      "dhanda mulmayecha",
      "dhanda mul mayecha",
      "prapancha khota ha",
      "mrugpani lobhe firto prani",
      "kanya sut dara dhan maze mithya vadito vani",
      "anti netil he yamdut na ye sange koni",
      "nirguna renuka kuldevi japlo mi nirwani",
      "panchabhutacha adhikar",
      "kela to satvar",
      "nayani dekhila aakar",
      "avagha to ishwar",
      "nahi sukha dukkha",
      "dehala kaicha ahankar",
      "pahe parmatma to dhani",
      "bhase shunyakar",
    ],
  },
  {
    number: "5",
    name: "जय जय हो नवचंडे",
    search_txt: [
      "jay jay ho navachande",
      "tripure chandamunda bal dandhe ho",
      "kali kilmish avakhande",
      "janani ashtadash bujdande ho",
      "jay jay vighna vitande",
      "survar vardayini chamunde ho",
      "shobati kari kodande",
      "sundar girivar kulmartande ho",
      "durjan durmati nikshan",
      "sajjan sharanagat sanrakshe ho",
      "trijagatankur kukshe durmat kantak sahkul bhakshe ho",
      "archak premal pakshe munijan manas nirgun rakshe ho",
      "kamalasani kamlakshe kamale sarvantari sakshe ho",
    ],
  },
  {
    number: "6",
    name: "जय जय हो जगदंबे। एकविरे रेणुका दुहिते।",
    search_txt: [
      "jay jay ho jagadambe",
      "ekvire renukaduhite o",
      "ruchikatmaja priyakante",
      "bhargav ramachi dwijmate o",
      "mulapith rahivas mrugppati baisali manduni thane o",
      "dattatrya varadayak sahastrabahu marduni prani o",
      "krushnamalika grami koribumika janoni may o",
      "shir kamaladik kaise puja ghesil jagrut pane o",
      "ama kasipur vasudhevaradhik adhik ho",
    ],
  },
  {
    number: "7",
    name: "नेससी तू पिवळा ।",
    search_txt: [
      "nesasi tu pivala",
      "patola haar shobe gala",
      "hati dharshil tu trishula",
      "bhali kumkum tila",
      "jay jay bhavani aho manaramani",
      "amravati vasini",
      "angi ghaluniya kancholi",
    ],
  },
  {
    number: "8",
    name: "अमरावती वासिनी ।",
    search_txt: [
      "amravati vasini",
      "maj la pav tu nirwani ho",
      "akhanda tujala dhyati",
      "munijan pathati ved purani ho",
      "kasturi malvata shendur rekhlase bhali ho",
      "navratnacha har kanthi shobhe to velhali ho",
    ],
  },
  {
    number: "9",
    name: "दुर्गे दुर्घट भारी ।",
    sub: "दुर्गेची नित्याची आरती ",
    search_txt: [
      "durge durghat bhari",
      "anath nathe ambe karuna vistari",
      "tarak sanjivani",
    ],
  },
  {
    number: "10",
    name: "पाहीन मी दर्शना । (भैरवी)",
    search_txt: [
      "pahina mi darshana",
      "pahin me darshana",
      "shankha chakra nijabhushana ho",
      "chausasthi she kula avghe deep gheuni ghati ho may",
      "udho bola udho",
      "udo bola udo",
      "name gondhal",
    ],
  },
  {
    number: "11",
    name: "तुळजाभवानीची आरती। शेवटची आरती (समापन)",
    search_txt: [
      "tulja ho may raja hi tulja",
      "charani das padle",
      "ambe charani anavat vaje jay jay tulja",
      "raja hi tulja",
      "krupavanta anubhuti mate",
      "aho charni daas he tulje",
      "charani anavat vaaje",
    ],
  },
  {
    number: "12",
    name: "ओवळा ओवळा देवी एकविरामाता ।",
    search_txt: [
      "oovala oovala devi ekviramata",
      "tu purvi bhavartha",
      "dhanya janardhana swami upasana keli",
      "renukecha bheti",
      "devi ekwira aali",
      "amaravati nagar zale shaktiche peeth",
      "aswin navaratri bahu yeti bhakta",
      "nirmal komal manas sakala labhave",
      "achut aarti karuti vandito bhave",
    ],
  },
  {
    number: "13",
    name: "अश्विन शुक्लपक्षी",
    search_txt: [
      "ashwin shukla pakshi",
      "amba baisali sinhasani ho",
      "pratipade pasuni",
      "ghatasthapana karuni ho",
      "ghatastapana kar ni ho",
      "bramha vishnu mahesh tuze pujan kariti ho",
      "udo mhanava udo amba bai mauli cha ho",
      "udho manava udho ambabai mauli cha ho",
      "anande khelasi kay mahima varnu ticha ho",
      "udho manava udho ambabai maulicha ho",
      "dwitiyeche divashi milati chaushasta yogini ho",
      "sakalamahde shreshta parashuramachi janani",
      "kastori malvat bhangi shendur bharila ho",
      "udokar garjati sakal chamunda miloni ho",
      "triteyeche divshi vrat upang lalita ho",
    ],
  },
  {
    number: "14",
    name: "ॐ जयो जयो माँ जगदम्बे",
    sub: "नवरात्रातील आरती २ री ",
    search_txt: [
      "om jayo jayo maa jagadambe",
      "om jayom jayom ma jagadambe",
      "om jay om jay om ma jagadambe",
      "jay adhya shakti",
      "ma jay aadya shakti",
      "akanda bramhand nipavya",
      "padave pandit ma",
      "dwitiya be swarup shivshakti janu",
      "bramha ganpati gaye har gaye har ma",
      "tritiya tranaswarup shiv tribhuvan ma betha",
      "trayastha ki triveni tu triveni ma",
    ],
  },
  {
    number: "15",
    name: "काशी आमुची",
    sub: "मंगळवारची आरती १ ली ",
    search_txt: [
      "kashi amuchi",
      "renuka mulapitha naika",
      "je je kalpil te",
      "tu desi iccha purna karisi",
      "mhanavuni prarthana",
      "pave maja dinashi",
      "ahima mahima",
      "balya bugadya shama",
      "sita saviti hi uma",
      "pave maja ghanashama",
      "aaise karoni uttar matapur sundar",
      "kaya nesali pitambar bahubhagye garasoli",
    ],
  },
  {
    number: "16",
    name: "ऐसी आरती होतसे",
    search_txt: [
      "aaisi aarti hotase",
      "jana yetase",
      "sant sajjan koti",
      "deva rishi aale manava aale danava",
      "aho bai cha bheti",
      "aeisi arti hotase jan yetase",
      "dongari deep pajali deep ujali",
      "deep ujaloni vela",
      "bhavatal divtya lagati",
      "vadye vajati vela",
    ],
  },
  {
    number: "17",
    name: "आरती ओवाळू । जननीला ।",
    search_txt: [
      "aarti oovalu janani la renukamatela",
      "mahurgadvasi jagatjanani vatsalyachi khani",
      "mahima varnu tuza",
      "kay mukhe varnu matela",
      "dinjanataraya avatarsi nana rupe dharsi",
      "nalage paar tula varnita bramha hi to thakala",
      "survarmuni yogi tuja dhyati karuna stotre gati",
      "danav nirdalnya rup dharsi ranchandi tu hosi sivharud sada",
      "ashtabhuja pralayankar tu jwala",
      "balak adhyani amhi tuze papache shiri ozhe",
      "aai jagadame sharan tula lagu de payala",
    ],
  },
  {
    number: "18",
    name: "आरती त्रिभुवन जननीची ।",
    search_txt: [
      "aarti tribhuvan janani chi bhavani aadi ambikechi",
      "sumangal samay aji aala patali janani matgruhala",
      "kanthi soubhagya ratnamala dipavi jyoti divati jwala",
      "malvati mali chandra bharla pahuni vrutti bhava harla",
      "mukhane udo udo bola",
      "aasamantat akhil jagatat navhe hridayat",
      "garjana ghado kahi sachi nirantar charnasi",
      "taranya bhakta butali avtare aadishakti maya",
      "pragatuni hridati aaj mazya lavite lahar hai gaya",
      "harvite gaan bhaan kaya unmani kavan jai vaya",
    ],
  },
  {
    number: "19",
    name: "ऐके जगदंबे । तुझे तुजप्रती ।",
    search_txt: [
      "aike jagadambe tuze tuzprati sangato o",
      "mana maze vyakul bhavani iccha fal magato o",
      "shrustivar hindata panthi dekhili ekachi naar o",
      "sola sahastra avatar dharun mhane mi kurnakar o",
      "jalavari aasan agnivari ti nidra kari o",
      "daityavar todar ubhi meruchi shikhari o",
      "dusariya vele amba aarud hastivari o",
      "ashtabhuja miraviti trishul damru triche kari o",
      "gala rundamala mukhi agnijwala dhari o",
      "ashuddha ghe ghataghata ubhi bhagirathi che tali ho",
      "eike jagdambe",
    ],
  },
  {
    number: "20",
    name: "आरती करा भवानीची ।",
    search_txt: [
      "aarti kara bhavanichi",
      "bhaktikari tripur sundarichi",
      "vidhi vhavasta adimaya vibudhajan aale paya",
      "staviti jana asur taap jaya lagale bhagavati guna gaya",
      "aaradhan kariti bhuvanasi",
      "bhavanigun katha staviti katha pavati gyan mithya",
      "nivari bhavabhranti sevakachi vruttikari shanti sevakachi",
      "devichi aagadha hi karni stavan karatasi aali dharni",
      "mari mahishasur dhari charni sakal asur pran harni",
      "asur vesanadhi dur karni",
      "nishumbhadika maari amika sakalakari sukha",
      "marduni sakal dannavasi nivari shija manvachi",
    ],
  },
  {
    number: "21",
    name: "उदो उदो येमाई ।",
    search_txt: [
      "udo udo yemai",
      "udho udho yemai",
      "adishakti ambabai ho",
      "trikon yantrakar ambe gad tuza sandar ho",
      "jwala nene dya gupta aahe bramhanand ho",
      "mana vinzal tirtha kaise shobhat aahe sthir ho",
      "panchapran jyoti divtya lavanyasahit ho",
      "adbhut he donar aasha trushna dekhe khore ho",
      "pudhe pahu jata shok bhayache dhandore ho",
      "kamakrodha dik vyaghrarupri mahavrunde ho",
      "santsamagam yoge mya dekhile matapur ho",
    ],
  },
  {
    number: "22",
    name: "आरती अंबा पदकमला ।",
    search_txt: [
      "aarti amba padkamla",
      "sevi sadbhave kamla",
      "sinhasani ubhi sunil gabha",
      "koti balark divya aabha",
      "pahta bhatka amit shobha",
      "takiti dravanadik lobha",
      "bhaktajan kirti parisuniya",
      "taki nijlok harijan shok deyi sadlok",
      "mansi aaicha bahugamla jo nar pdambuji ramla",
      "kamla naam sada smarata na badhi tyasi kada smarata",
      "vratha ya abhimani marta jail vrarthachi hi narta",
      "mhanuniya sharan ridha tijla",
      "karuni padi naman aarpan suman vishay he vaman",
      "manuni sansar sharamla taki haripadi seve vemla",
    ],
  },
  {
    number: "23",
    name: "आरती अंबाबाईची । त्रिपुर सुंदरी ।",
    search_txt: [
      "aarti ambabai chi tripur sundari renukechi",
      "ujalonni hridayagyan jyoti lavu vishaymoh vati",
      "smaruni mangalgun chitti karu ekagra sakalvrutti",
      "vivek akalun svamati jeevan he apurva nijpriti",
      "chalo ho bhakti karu ichi tripur sundari renukeche",
      "mani he jadle ambe charne vege zali durit hani",
      "range nisidini gundani tehe hoy dhanya vani",
      "tuajvin anya nase koni dina tari tu nirwani",
      "bhave kaas dharu ichi tripursundari renukechi",
    ],
  },
  {
    number: "24",
    name: "उदो उदो रेणुकेचा ।",
    search_txt: [
      "udo udo renukecha amravati vas jicha",
      "kantari vas kamala divtya ujaloni gondhal kela",
      "baraya tera sajati pude renuchi duhiti",
      "haar gala kavadiyanchi mugutamani bahu ratnacha",
      "lagena anta jicha yogi yagna arpiti pancha",
      "mohanmaya adishakti ved neti neti bolti",
      "mohinirup dharan kele bhasmasura tadan kele",
      "hemgouri duhita soubhagiyale thir anand garjiyele",
      "shankar bramha vishnu pujiti narard ubha sanmukh gati",
      "upama saje chandanyachi jaise pankaj kamalinichi",
    ],
  },
  {
    number: "25",
    name: "ओवाळू आरती । शिवसांबे ।",
    search_txt: [
      "oovalu aarti shivsambe trigun rupi rambhe",
      "nandurigad nande jagadambe",
      "jay ho jay shri ambe",
      "ashtotar shat tirthe hi nirmele ho aai",
      "navanathasi ho kaliyugi shabari vidya deyi",
      "jadmud taraya basli ho bhakta prema lavi",
      "gajmukhi herambe jagadambe",
      "sanmukh purvesi baisale markandeya muni",
      "saptashatichya pathacha parishe madur dwani",
      "shivalay tirthi snanasi karito dev muni",
      "durge mularambhe jagadambe ",
      "parvat shikhari dwajahi chaitri kojagiri",
      "hiravi paithani nesali bahu alankari",
      "nath sajyachi nashiki sragalasari",
      "bharurangi range jagadambe",
    ],
  },
  {
    number: "26",
    name: "आरती करू एकविरा ।",
    search_txt: [
      "aarati karu ekvira ujaloni jyoti karpura",
      "aarti karu ekwira ujloni joti karpura",
      "bhimkachi ji kul amba yeuni baisali jagadamba",
      "teje lopavi ravi bimba lajavi chandramukha amba",
      "nesali pitambara pivla lyali kancholi gala garasoli lavili bhali",
      "malvat keshari sara bhangi bharlya shendura",
      "rukhmini pujatase amba sthapuni sanidha jalkumbha",
      "lavuni kardalichya stambha thevi sanidha falarambha",
      "shobhati ikshudanda tya varti",
      "bandhuni mal vajavi tal lavi depmal",
      "jogava maguni ghe sara gondhal ghalin parivara",
      "prarthi bhimak nrup bala dakhavi janani gopala",
      "nyahaluni pahe nejdola ghatlya sumanancha mala",
      "bhetta ramanath pahi",
    ],
  },
  {
    number: "27",
    name: "आरती करितो जगदंबे ।",
    search_txt: [
      "aarti karito jagadambe bhagawati kulaswamini ambe",
      "hari kalpanti kari shayana sagari nabhi kamalsadana",
      "prarthana kari chaturvadana karaya madhukaitabha hanana",
      "ghei dhav vishnumaye zani yevuni bhaya varuni aasur maruni",
      "ambe tari tari majla vadata abhay dile tyala",
      "jinkun sarva deva samari mahishasur to rajyakari",
      "pavle kopa shambhu hari sakal sur anshe divya nari",
      "hovuni mahishasur vadhila haruni aapada soukya sampadha sura de sada",
      "hota te nat tav payi mahishasur mardini aai",
      "vadhile shumba nishumbhasi anik dushta daitya tyasi",
      "rakshile nijabhakta janasi sarvada deuni vijayasi",
      "ambe mahima tava gata",
      "hoi anand tuthe bhavbandha gyan makarand",
      "houni mukt kari majala daas ha krushna sharan tujla",
    ],
  },
  {
    number: "28",
    name: "आरती श्री जगदंबेची ।",
    search_txt: [
      "aarti shri jagadambe chi devi mahalaxmi chi",
      "suvarna sinhasani baisali angi pitambar lyali",
      "sundar hemamukut ghali vilase chandahar mouli",
      "jarichi hirvi kancholi",
      "kumkumtilak thalak nidhali",
      "uthi keshri ani kasturi dise gojori",
      "murtich paramanandachi devi mahalaxmichi",
      "kanthi haar champakacha gulab jai mogaricha",
      "tasach moutikya rantnacha vaksha sthali shobhe sacha",
      "vadani mandasmit vilse nijajana sukhavi vishvase",
      "khadag chakra dhari taapdukhha hari adya nashkari",
      "krupalu mauli dinachi devi mahalaxmi chi",
    ],
  },
  {
    number: "29",
    name: "आरती महालक्ष्मीची ।",
    search_txt: [
      "aarti mahalaxmi chi krupalu jeshtha kanistha chi",
      "adimay tu jagadambe asashi jagaswamini ambe",
      "harihar mangal aarambhe pujiti twatpad avilambe",
      "varniti guna ved chari",
      "devamuni rava dharuni drud bhava gheti padi dhav",
      "kariti aas darshanachi mata jagapalak sachi",
      "kati pat tapta hemavarni kanchuki haar pachuvarni",
      "mudra khadi nilvarni manimay balya kap karni",
      "vilase chandrahar kanthi",
      "shashisama vadan pahata nayan hoti tallin",
      "karantari shobha kankanachi mastaki jali motiyachi",
    ],
  },
  {
    number: "30",
    name: "औसे देखिली ।",
    search_txt: [
      "aaise dekhili bhavani vindyachal vasini",
      "ouse dekhili",
      "chavda bhuvananchi swamini mahishasur mardini",
      "aeise dekili",
      "khopa bharuni patoli surang tyala choli",
      "khachit ratnachi zhalali patal shobhe bhari",
      "sarilal chitank sakali kanthi ekawali",
      "galyat sobhatase garasoli tilak sobhe bali",
      "karva kardoda bahuranda bhavar rakhi muda",
      "charani bridacha todara dhak daitya vara",
      "lajja vatatase chandasi pahuni mukha kamalasi",
      "prasanna hovoni lankeshi var de go vindasi",
    ],
  },
];
